name: tiny_pytorch_nerf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - numpy
  - matplotlib
  - pip
  - pip:
    - tqdm
    - tensorflow
    - imageio-ffmpeg
    - torch
